version: "3"
services:
  es:
    build: ./es
    container_name: elasticsearch-v8010
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=es-docker-cluster
      - "ES_JAVA_OPTS0=-Xms4096m -Xms4096m"
      - xpack.security.enabled=false
      - http.port=9200
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.0
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch-v8010:9200
volumes:
  es-data: null
